// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2U5e9XjLZwXmVrjpN-24tmLReliVugrg',
    appId: '1:558046741728:web:88cad3daf02b9c8d9e7c85',
    messagingSenderId: '558046741728',
    projectId: 'flutter-3c649',
    authDomain: 'flutter-3c649.firebaseapp.com',
    databaseURL: 'https://flutter-3c649-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-3c649.appspot.com',
    measurementId: 'G-VZL936RKPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgxLMy8cuUEEDeYvC5RVQjUrHs0EEr1o0',
    appId: '1:558046741728:android:e8a20b6921ffbcb89e7c85',
    messagingSenderId: '558046741728',
    projectId: 'flutter-3c649',
    databaseURL: 'https://flutter-3c649-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-3c649.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfe327LzH8cJzlJ3G_309CHVWDndkrgJQ',
    appId: '1:558046741728:ios:9f148df23ef065189e7c85',
    messagingSenderId: '558046741728',
    projectId: 'flutter-3c649',
    databaseURL: 'https://flutter-3c649-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-3c649.appspot.com',
    iosBundleId: 'com.example.bengkelPakBowo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfe327LzH8cJzlJ3G_309CHVWDndkrgJQ',
    appId: '1:558046741728:ios:9f148df23ef065189e7c85',
    messagingSenderId: '558046741728',
    projectId: 'flutter-3c649',
    databaseURL: 'https://flutter-3c649-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-3c649.appspot.com',
    iosBundleId: 'com.example.bengkelPakBowo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2U5e9XjLZwXmVrjpN-24tmLReliVugrg',
    appId: '1:558046741728:web:5380ae1fb1007f819e7c85',
    messagingSenderId: '558046741728',
    projectId: 'flutter-3c649',
    authDomain: 'flutter-3c649.firebaseapp.com',
    databaseURL: 'https://flutter-3c649-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-3c649.appspot.com',
    measurementId: 'G-9L960ZVQCJ',
  );
}
